# Generated by Django 4.2.13 on 2024-06-17 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('age', models.PositiveSmallIntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('nationality', models.CharField(max_length=20)),
                ('teacherID', models.PositiveSmallIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('specialization', models.CharField(max_length=25)),
                ('date_of_birth', models.DateField()),
                ('years_of_experience', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
