# Generated by Django 4.2.13 on 2024-08-08 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='age',
        ),
        migrations.AddField(
            model_name='teacher',
            name='bank_account_number',
            field=models.TextField(default=456765),
        ),
        migrations.AddField(
            model_name='teacher',
            name='bio',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='teacher',
            name='contact',
            field=models.CharField(default='075634252693', max_length=20),
        ),
        migrations.AddField(
            model_name='teacher',
            name='phone_number',
            field=models.PositiveIntegerField(default='078654323412'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='profile',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
