# Generated by Django 4.2.13 on 2024-08-08 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=20)),
                ('class_representative', models.CharField(max_length=20)),
                ('class_size', models.CharField(max_length=20)),
                ('class_capacity', models.PositiveSmallIntegerField()),
                ('room_number', models.CharField(max_length=20)),
                ('class_vision', models.TextField()),
                ('class_mission', models.TextField()),
                ('class_enrollment', models.CharField(max_length=20)),
                ('class_artwork', models.CharField(max_length=20)),
                ('color_of_chairs', models.CharField(max_length=25)),
                ('number_of_laptops', models.PositiveSmallIntegerField()),
                ('number_of_windows', models.PositiveSmallIntegerField()),
                ('number_of_television', models.PositiveSmallIntegerField()),
                ('number_of_electronic_equipments', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
