# Generated by Django 4.2.13 on 2024-08-08 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_attendance',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_prior_skills',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_trainer',
        ),
        migrations.AddField(
            model_name='course',
            name='assessment_requirements',
            field=models.CharField(default='Default Value Here', max_length=255),
        ),
        migrations.AddField(
            model_name='course',
            name='classes_hours',
            field=models.DurationField(default=2, max_length=5),
        ),
        migrations.AddField(
            model_name='course',
            name='course_attendance_per_week',
            field=models.CharField(default=5, max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_description',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_module',
            field=models.TextField(max_length=25),
        ),
    ]
