# Generated by Django 4.2.13 on 2024-08-04 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('course', models.CharField(max_length=100)),
                ('classroom', models.CharField(max_length=50)),
                ('day_of_week', models.CharField(max_length=20)),
            ],
        ),
    ]
