# Generated by Django 4.2.13 on 2024-08-08 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_student_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='code',
        ),
        migrations.RemoveField(
            model_name='student',
            name='country',
        ),
        migrations.RemoveField(
            model_name='student',
            name='firstname',
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.CharField(max_length=25),
        ),
    ]
